# Generated by Django 3.2.7 on 2021-10-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulo', '__first__'),
        ('area', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=50)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo')),
            ],
        ),
    ]
