# Generated by Django 3.2.7 on 2021-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
